#!/usr/bin/bash
if [ $# == 0 -o "$1" == "-h" -o "$1" == "--help" ]; then
    echo "          confman"
    echo '          /// \\\'
    echo "configuration manager"
    echo ""
    echo "Usage:"
    echo "-h | --help | no arguments = show this message"
    echo "Two options are allowed:"
    echo "    -n | --nono  = list what it would do but don't do it"
    echo "    -c | --clean = cleanup (delete) the backup files it would normally generate. DOES NOT do anything else"
    echo "  They are mutually exclusive!"
    echo "Then you must specify the configuration file to read."
    echo ""
    echo "Example: \`confman -c configuration'"
    exit 1
fi

if [ "$1" == "-n" ]; then
    function routine() {
	[ -e "$(eval echo "$2")" -o -L "$(eval echo "$2")" ] \
	    && echo "mv \"$(eval echo "$2")\" \"$(eval echo "$2.backup")\""
	echo "ln -s \"$(eval echo "$basedir/$1")\" \"$(eval echo "$2")\""
    }
    shift
elif [ "$1" == "-c" ]; then
    function routine() {
	[ -e "$(eval echo "$2")" -o -L "$(eval echo "$2")" ] \
	    && rm "$(eval echo "$2")" "$(eval echo "$2.backup")"
    }
    shift
else
    function routine() {
	[ -e "$(eval echo "$2")" -o -L "$(eval echo "$2")" ] \
	    && mv "$(eval echo "$2")" "$(eval echo "$2.backup")"
	ln -s "$(eval echo "$basedir/$1")" "$(eval echo "$2")"
    }
fi

numLines="$(cat "$1" | wc -l)"
basedir="$(head -n 1 "$1" | tail -n 1)"

for (( i=2; i <= $numLines + 1; i++ )); do
    line="$(head -n $i "$1" | tail -n 1)"
    if [ ! -z "$line" ]; then
	first="$(echo "$line" | perl -pe "s/^(?:\"(.*)\"|'(.*)'|([^ ]+)).*$/\$1\$2\$3/")"
	second="$(echo "$line" | perl -pe "s/^.*?(?:\"(.*)\"|'(.*)'|([^ ]+))$/\$1\$2\$3/")"
	routine "$first" "$second"
    fi
done
